const dataProject1 = {
  title: "Administration System",
  desc: "Composed of different modules to provide diverse functions of the administration system.",
  imgList: [
    { src: "/projects/project_1/p1_01.png", name: "Dashboard" },
    { src: "/projects/project_1/p1_02.png", name: "Dashboard 2" },
    { src: "/projects/project_1/p1_03.png", name: "Customer List" },
    { src: "/projects/project_1/p1_04.png", name: "New Customer" },
    { src: "/projects/project_1/p1_05.png", name: "Customer Detail" },
    { src: "/projects/project_1/p1_06.png", name: "Order History" },
    { src: "/projects/project_1/p1_07.png", name: "Quotation List" },
    { src: "/projects/project_1/p1_08.png", name: "New Quotation Client Info" },
    {
      src: "/projects/project_1/p1_09.png",
      name: "New Quotation Items & Price",
    },
    { src: "/projects/project_1/p1_10.png", name: "Quotation Menu" },

    { src: "/projects/project_1/p1_11.png", name: "Invoice List" },
    { src: "/projects/project_1/p1_12.png", name: "Invoice Menu" },
    { src: "/projects/project_1/p1_13.png", name: "Invoice Bulk Action" },
    { src: "/projects/project_1/p1_14.png", name: "Check Payment" },
    { src: "/projects/project_1/p1_15.png", name: "Make Bulk Payment" },
    { src: "/projects/project_1/p1_16.png", name: "Credit Note" },
    { src: "/projects/project_1/p1_17.png", name: "Supplier List" },
    { src: "/projects/project_1/p1_18.png", name: "New Supplier" },
    { src: "/projects/project_1/p1_19.png", name: "Edit Supplier" },
    { src: "/projects/project_1/p1_20.png", name: "Purchase Order List" },

    { src: "/projects/project_1/p1_21.png", name: "New Purchase Order" },
    { src: "/projects/project_1/p1_22.png", name: "Purchase Order Menu" },
    { src: "/projects/project_1/p1_23.png", name: "Promo Code" },
    { src: "/projects/project_1/p1_24.png", name: "New Promo Code" },
    { src: "/projects/project_1/p1_25.png", name: "Joblist" },
    {
      src: "/projects/project_1/p1_26.png",
      name: "Joblist ( View Completed )",
    },
    { src: "/projects/project_1/p1_27.png", name: "Artwork Management" },
    { src: "/projects/project_1/p1_28.png", name: "Customer Store List" },
    { src: "/projects/project_1/p1_29.png", name: "New Store" },
    { src: "/projects/project_1/p1_30.png", name: "Delivery Order List" },

    { src: "/projects/project_1/p1_31.png", name: "Delivery Order Menu" },
    { src: "/projects/project_1/p1_32.png", name: "Product Category" },
    { src: "/projects/project_1/p1_33.png", name: "New Category Part 1" },
    { src: "/projects/project_1/p1_34.png", name: "New Category Part 2" },
    { src: "/projects/project_1/p1_35.png", name: "Product List" },
    { src: "/projects/project_1/p1_36.png", name: "New Product" },
    { src: "/projects/project_1/p1_37.png", name: "New Product Part 2" },
    { src: "/projects/project_1/p1_38.png", name: "New Product Image" },
    { src: "/projects/project_1/p1_39.png", name: "Edit Product" },
    { src: "/projects/project_1/p1_40.png", name: "Supplies List" },

    { src: "/projects/project_1/p1_41.png", name: "New Supplies" },
    { src: "/projects/project_1/p1_42.png", name: "Update Product Cost" },
    { src: "/projects/project_1/p1_43.png", name: "Edit Supplies Info" },
    { src: "/projects/project_1/p1_44.png", name: "Edit Price & Sizes" },
    { src: "/projects/project_1/p1_45.png", name: "Edit Price & Sizes Part 2" },
    { src: "/projects/project_1/p1_46.png", name: "Internal Use Product" },
    { src: "/projects/project_1/p1_47.png", name: "Stock Balance" },
    { src: "/projects/project_1/p1_48.png", name: "Low Stock List" },
    { src: "/projects/project_1/p1_49.png", name: "Stock Costing" },
    { src: "/projects/project_1/p1_50.png", name: "Stock Value" },

    { src: "/projects/project_1/p1_51.png", name: "Stock Usage" },
    {
      src: "/projects/project_1/p1_52.png",
      name: "Stock Adjustment ( Searching )",
    },
    { src: "/projects/project_1/p1_53.png", name: "Stock Adjustment" },
    {
      src: "/projects/project_1/p1_54.png",
      name: "Select Product for Bulk Adjustment",
    },
    { src: "/projects/project_1/p1_55.png", name: "Bulk Adjustment" },
    { src: "/projects/project_1/p1_56.png", name: "Stock Audit" },
    { src: "/projects/project_1/p1_57.png", name: "Stock Incoming" },
    { src: "/projects/project_1/p1_58.png", name: "Stock Check" },
    { src: "/projects/project_1/p1_59.png", name: "Stock Check ( Submitted )" },
    { src: "/projects/project_1/p1_60.png", name: "Stock Check ( Editing )" },

    { src: "/projects/project_1/p1_61.png", name: "Expense List with Filter" },
    { src: "/projects/project_1/p1_63.png", name: "Expense List" },
    { src: "/projects/project_1/p1_64.png", name: "Payment Collected" },
    { src: "/projects/project_1/p1_65.png", name: "GST Report" },
    { src: "/projects/project_1/p1_66.png", name: "Profit & Loss" },
    { src: "/projects/project_1/p1_67.png", name: "Acoount Aging Report" },
    { src: "/projects/project_1/p1_68.png", name: "Customer SOA" },
    { src: "/projects/project_1/p1_69.png", name: "Invoices Report" },
    { src: "/projects/project_1/p1_70.png", name: "Subcon Report" },

    { src: "/projects/project_1/p1_71.png", name: "Commission Report" },
    { src: "/projects/project_1/p1_72.png", name: "General Setting" },
    { src: "/projects/project_1/p1_73.png", name: "General Setting ( GST )" },
    { src: "/projects/project_1/p1_74.png", name: "General Setting Part 2" },
    { src: "/projects/project_1/p1_75.png", name: "Product Setting" },
    { src: "/projects/project_1/p1_76.png", name: "Staff Setting" },
    { src: "/projects/project_1/p1_77.png", name: "Workgroup Setting" },
    { src: "/projects/project_1/p1_78.png", name: "New Workgroup" },
    { src: "/projects/project_1/p1_79.png", name: "Edit Workgroup" },
  ],
};

export default dataProject1;
