# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: NODE CICD

on: [push, pull_request]
env:
  SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
  SENDGRID_EMAIL_FROM: ${{ secrets.SENDGRID_EMAIL_FROM }}
  SENDGRID_EMAIL_TO: ${{ secrets.SENDGRID_EMAIL_TO }}
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - name: Install, Lint
        run: |
          npm install
          npm run lint
      - name: Build
        run: |
          echo -e "SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}\nSENDGRID_EMAIL_FROM=${{ secrets.SENDGRID_EMAIL_FROM }}\nSENDGRID_EMAIL_TO=${{ secrets.SENDGRID_EMAIL_TO }}" > .env.local
          npm run build
      # - name: Deploy AWS
      #   uses: easingthemes/ssh-deploy@main
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #     SOURCE: ".next/"
      #     REMOTE_HOST: ${{ secrets.SSH_HOST }}
      #     REMOTE_USER: ${{ secrets.USER }}
      #     TARGET: /home/${{ secrets.USER }}/projects/portfolio
